	MACRO
	INCR_D	&MEM_VAL, &INCR_VAL=,	&REG=AREG
	MOVER	&REG, &MEM_VAL
	ADD	&REG, &INCR_VAL
	MOVEM	&REG,	&MEM_VAL
	MEND
	MACRO
	COMPUTE	&FIRST,	&SECOND,	&THIRD=100
	MOVEM	BREG,	&THIRD
	INCR_D	&FIRST,	&INCR_VAL=101,	&REG=BREG
	INCR_D	500,	&INCR_VAL=501
	MOVER	BREG,	&THIRD
	ADD	BREG,	&THIRD
	MEND
	INCR_D	AREA,	&INCR_VAL=3
	COMPUTE	AREA, 3
	END
